openapi: 3.0.1
info:
  title: Developer Plugin
  description: A plugin to generate PRs for github projects
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /code:
    post:
      summary: Update code in project
      operationId: code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: Prompt for code tasking to be assigned to coder, do not micromanage
      responses:
        '200':
          description: Coding Task Started
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  /list_files:
    post:
      summary: List files in a directory
      operationId: list_files
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                base_directory:
                  type: string
                  description: Optional base directory to list files from, defaults to project directory
                regexp:
                  type: string
                  description: Optional regular expression to filter the files
                limit:
                  type: integer
                  description: Optional limit for the number of files to return
      responses:
        '200':
          description: Files listed successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    path:
                      type: string
                      description: The file path
                    ctime:
                      type: string
                      format: date-time
                      description: The file creation time
                    mtime:
                      type: string
                      format: date-time
                      description: The file modification time
                    size:
                      type: integer
                      description: The file size in bytes
  /get:
    post:
      summary: Get the content of a file
      operationId: get_file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  description: The file name to retrieve the content of
      responses:
        '200':
          description: File content retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: The content of the file
